# File: .github/workflows/repo-sync.yml

on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "git@github.com:PennState/jms-tools.git"
        SOURCE_BRANCH: "refs/remotes/source/*"
        DESTINATION_REPO: "git@git.psu.edu:mirrored/jms-tools.git"
        DESTINATION_BRANCH: "refs/heads/*"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
